// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5QBw5XegdTGvaDSMMWdXde4LtaNgJgq4',
    appId: '1:1042149220956:web:8dd74e0618f30609d5fc99',
    messagingSenderId: '1042149220956',
    projectId: 'flutter2026-ed422',
    authDomain: 'flutter2026-ed422.firebaseapp.com',
    storageBucket: 'flutter2026-ed422.firebasestorage.app',
    measurementId: 'G-C3BE77BESJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALXR_bKo460ReOcV6EQPSwPe-YH1pxV8A',
    appId: '1:1042149220956:android:7627250e30d33c79d5fc99',
    messagingSenderId: '1042149220956',
    projectId: 'flutter2026-ed422',
    storageBucket: 'flutter2026-ed422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqNxx2aAiG6P29sDkiPxSTgOnw9x6k8Tc',
    appId: '1:1042149220956:ios:20224be7aeaec9e4d5fc99',
    messagingSenderId: '1042149220956',
    projectId: 'flutter2026-ed422',
    storageBucket: 'flutter2026-ed422.firebasestorage.app',
    iosBundleId: 'com.flutter2026.flutter2026',
  );
}
